[project]
name = "unitree-vision-rl"
version = "0.1.0"
description = "Unitree Go2 Vision RL in mjlab"
readme = "README.md"
authors = [
    { name = "Matthew Gomez", email = "matthewgomezm10@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mjlab>=1.6.0",
    "wandb>=0.22.3,<0.29",
]

[project.scripts]
unitree-vision-rl = "unitree_vision_rl:main"

[project.entry-points."mjlab.tasks"]
unitree_vision_rl = "unitree_vision_rl"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
